# This is a basic workflow to help you get started with Actions

name: test

# 触发条件
on:
  # workflow 通过按键触发
  workflow_dispatch:

# 需要进行的job内容
jobs:
  # workflow 的一个job叫 run_in_linux
  run_on_linux:
    # 在什么平台上执行，ubuntu，mac, win都可以支持。
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"
          architecture: "x64"
      - name: Install dependencies
        run: |
          pwd
          ls
          pip install requests bs4 lxml playwright
          python3 --version
          pip list
          python3 -m playwright install
          python3 -m playwright help
          playwright install-deps
      - name: run python script
        run: |
          python3 v2note_update.py
          ls
      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "Update v2note file `date`"
          git pull --rebase
          git push
