# This is a basic workflow to help you get started with Actions

name: test

# 触发条件
on:
  # workflow 通过按键触发
  workflow_dispatch:

# 需要进行的job内容
jobs:
  # workflow 的一个job叫 run_in_linux
  run_on_linux:
    # 在什么平台上执行，ubuntu，mac, win都可以支持。
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"
          architecture: "x64"
      - name: test show
        run: |
          pwd
          ls
          # pip install pip -U 升级安装pip
          pip install requests
          python3 --version
          pip list
          
